### ISSUE TITLE
incorrect nested return? 

### ISSUE THREAD

**Issue by mbannert** [banboo-data/r4googleads#28]
Is the return of 

```r
g_query <- "SELECT
                campaign.name, 
                campaign.status,
                segments.device, 
                metrics.impressions,
                metrics.clicks, 
                metrics.ctr,
                metrics.average_cpc, 
                metrics.cost_micros
              FROM campaign
              WHERE segments.date DURING LAST_30_DAYS
              AND metrics.impressions > 0
              PARAMETERS include_drafts=true"
```

and 

```r
d <- query_google_ads(
  mcc_id = '***-***-****', # Google Ads My Client Center ID
  google_auth = google_auth,
  service = query_service,
  raw_data = F
)

```

correct?  In end up getting a **nested** data.frame that appears to be nested for no reason. Is that the case? 

```r
> str(as.data.frame(data[[1]]))
'data.frame':	6 obs. of  3 variables:
 $ campaign:'data.frame':	6 obs. of  3 variables:
  ..$ resourceName: chr  "customers/*********/campaigns/354500548" "customers/*********/campaigns/14704583758" "customers/*********/campaigns/354500548" "customers/*********/campaigns/14704583758" ...
  ..$ status      : chr  "ENABLED" "ENABLED" "ENABLED" "ENABLED" ...
  ..$ name        : chr  "Brands" "google_shopping_de" "Brands" "google_shopping_de" ...
 $ metrics :'data.frame':	6 obs. of  5 variables:
  ..$ clicks     : chr  "139" "33" "628" "64" ...
  ..$ costMicros : chr  "35770000" "2190000" "159470000" "6370000" ...
  ..$ ctr        : num  0.0631 0.0141 0.0828 0.0105 0.0474 ...
  ..$ averageCpc : num  257338 66364 253933 99531 262000 ...
  ..$ impressions: chr  "2204" "2339" "7583" "6068" ...
 $ segments:'data.frame':	6 obs. of  1 variable:
  ..$ device: chr  "DESKTOP" "DESKTOP" "MOBILE" "MOBILE" ...
> unlist(data, recursive = F)
```

If so, don't we need to auto *cbind* it somehow? 
Like 

```r
do.call("cbind",unlist(data, recursive = F))
```

for

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> campaign.resourceName </th>
   <th style="text-align:left;"> campaign.status </th>
   <th style="text-align:left;"> campaign.name </th>
   <th style="text-align:left;"> metrics.clicks </th>
   <th style="text-align:left;"> metrics.costMicros </th>
   <th style="text-align:right;"> metrics.ctr </th>
   <th style="text-align:right;"> metrics.averageCpc </th>
   <th style="text-align:left;"> metrics.impressions </th>
   <th style="text-align:left;"> device </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> customers/*********/campaigns/354500548 </td>
   <td style="text-align:left;"> ENABLED </td>
   <td style="text-align:left;"> Brands </td>
   <td style="text-align:left;"> 139 </td>
   <td style="text-align:left;"> 35770000 </td>
   <td style="text-align:right;"> 0.0630672 </td>
   <td style="text-align:right;"> 257338.13 </td>
   <td style="text-align:left;"> 2204 </td>
   <td style="text-align:left;"> DESKTOP </td>
  </tr>
  <tr>
   <td style="text-align:left;"> customers/*********/campaigns/14704583758 </td>
   <td style="text-align:left;"> ENABLED </td>
   <td style="text-align:left;"> google_shopping_de </td>
   <td style="text-align:left;"> 33 </td>
   <td style="text-align:left;"> 2190000 </td>
   <td style="text-align:right;"> 0.0141086 </td>
   <td style="text-align:right;"> 66363.64 </td>
   <td style="text-align:left;"> 2339 </td>
   <td style="text-align:left;"> DESKTOP </td>
  </tr>
  <tr>
   <td style="text-align:left;"> customers/*********/campaigns/354500548 </td>
   <td style="text-align:left;"> ENABLED </td>
   <td style="text-align:left;"> Brands </td>
   <td style="text-align:left;"> 628 </td>
   <td style="text-align:left;"> 159470000 </td>
   <td style="text-align:right;"> 0.0828168 </td>
   <td style="text-align:right;"> 253933.12 </td>
   <td style="text-align:left;"> 7583 </td>
   <td style="text-align:left;"> MOBILE </td>
  </tr>
  <tr>
   <td style="text-align:left;"> customers/*********/campaigns/14704583758 </td>
   <td style="text-align:left;"> ENABLED </td>
   <td style="text-align:left;"> google_shopping_de </td>
   <td style="text-align:left;"> 64 </td>
   <td style="text-align:left;"> 6370000 </td>
   <td style="text-align:right;"> 0.0105471 </td>
   <td style="text-align:right;"> 99531.25 </td>
   <td style="text-align:left;"> 6068 </td>
   <td style="text-align:left;"> MOBILE </td>
  </tr>
  <tr>
   <td style="text-align:left;"> customers/*********/campaigns/354500548 </td>
   <td style="text-align:left;"> ENABLED </td>
   <td style="text-align:left;"> Brands </td>
   <td style="text-align:left;"> 20 </td>
   <td style="text-align:left;"> 5240000 </td>
   <td style="text-align:right;"> 0.0473934 </td>
   <td style="text-align:right;"> 262000.00 </td>
   <td style="text-align:left;"> 422 </td>
   <td style="text-align:left;"> TABLET </td>
  </tr>
  <tr>
   <td style="text-align:left;"> customers/*********/campaigns/14704583758 </td>
   <td style="text-align:left;"> ENABLED </td>
   <td style="text-align:left;"> google_shopping_de </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:right;"> 0.0000000 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:left;"> 234 </td>
   <td style="text-align:left;"> TABLET </td>
  </tr>
</tbody>
</table>

Or would that make the functions less flexible for different outputs? If so we can try to detect the case where we can have a single table and run *do.call* ? 

What do you think @jburkhardt ? (look the pkgdown branch)

**Comment by jburkhardt** [comment]
@mbannert Really good discovery! Thanks!
I recommend to apply your fix to the `googleAdsSearch()` service constructor only. https://github.com/banboo-data/r4googleads/commit/604ce6092e13d5903f6ade6ed91d0cc39e3126f4

Other services like `googleAdsFields` it is more convenient to return a list.
Example:
```
# Explore Report Schema
tbl_schema_service = googleAdsFields(tbl = "campaign", api_version = 'v9')

tbl_schema <- query_google_ads(
  mcc_id = 'XXX-XXX-XXX',
  google_auth = tbl_schema_service,
  service = my_service_2,
  raw_data = F
)
```

**Comment by jburkhardt** [comment]
ToDo:
* [ ] Update https://github.com/banboo-data/r4googleads/blob/pkgdown/index.md?plain=1#L146 with the table above as return a dataframe now instead of nested list.
